version: '3.8'
services:
  reddit-memestic:
    build: .
    container_name: reddit-memestic
    env_file:
      - .env.prod
    ports:
      - "4000:4000"
    volumes:
      - ./sent_memes.json:/usr/src/app/sent_memes.json
    restart: unless-stopped 
    